"""
Authentication service layer.

All functions are pure async; they accept an AsyncSession and return domain objects.
No HTTP knowledge here — sessions, tokens, and cookies are handled by the endpoint layer.
"""

import uuid
from datetime import UTC, datetime, timedelta

from sqlalchemy import select
from sqlalchemy import update as sql_update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core import storage
from app.core.exceptions import (
    BadRequestError,
    ConflictError,
    NotFoundError,
    UnauthorizedError,
)
from app.core.security import hash_password, verify_password
from app.models.auth_session import AuthSession
from app.models.institution import Institution
from app.models.membership import Membership
from app.models.user import User
from app.schemas.auth import (
    ChangePasswordRequest,
    LoginRequest,
    ProfileUpdateRequest,
    RegisterRequest,
    SignupRequest,
)


def _session_expires_at() -> datetime:
    return datetime.now(UTC) + timedelta(days=7)


# ---------------------------------------------------------------------------
# Register — creates institution + admin user in one transaction
# ---------------------------------------------------------------------------


async def register(
    db: AsyncSession,
    data: RegisterRequest,
    ip_address: str | None,
    user_agent: str | None,
) -> tuple[User, Membership, AuthSession]:
    """
    Atomically creates:
      1. Institution (name, slug)
      2. User (email, hashed_password, full_name)
      3. Membership (user ↔ institution, role=institution_admin)
      4. AuthSession (establishes the initial login session)
    """
    # Check email uniqueness
    result = await db.execute(select(User).where(User.email == str(data.email)))
    if result.scalar_one_or_none() is not None:
        raise ConflictError("An account with this email address already exists.")

    # Check slug uniqueness
    result = await db.execute(select(Institution).where(Institution.slug == data.institution_slug))
    if result.scalar_one_or_none() is not None:
        raise ConflictError(
            f"The institution slug '{data.institution_slug}' is already taken. "
            "Please choose a different one."
        )

    # Create institution (uuid4 generated by Python at object-creation time)
    institution = Institution(
        name=data.institution_name,
        slug=data.institution_slug,
    )
    db.add(institution)
    await db.flush()  # Insert institution before membership references it

    # Create user
    user = User(
        email=str(data.email),
        hashed_password=hash_password(data.password),
        full_name=data.full_name,
    )
    db.add(user)
    await db.flush()  # Insert user before membership references it

    # Create membership (institution_admin for first registrant)
    membership = Membership(
        user_id=user.id,
        institution_id=institution.id,
        role="institution_admin",
        status="active",
    )
    db.add(membership)

    # Create auth session
    auth_session = AuthSession(
        user_id=user.id,
        institution_id=institution.id,
        ip_address=ip_address,
        user_agent=user_agent,
        expires_at=_session_expires_at(),
    )
    db.add(auth_session)

    await db.commit()

    # Refresh to pick up DB-set defaults (timestamps, etc.)
    await db.refresh(user)
    await db.refresh(membership)
    await db.refresh(auth_session)

    return user, membership, auth_session


# ---------------------------------------------------------------------------
# Signup — open student self-registration into the existing institution
# ---------------------------------------------------------------------------


async def signup(
    db: AsyncSession,
    data: SignupRequest,
    ip_address: str | None,
    user_agent: str | None,
) -> tuple[User, Membership, AuthSession]:
    """
    Open student self-registration. Unlike ``register`` (which provisions a new
    institution + admin), this enrols a brand-new **student** into the single
    existing institution. Atomically creates:
      1. User (email, hashed_password, full_name)
      2. Membership (user ↔ existing institution, role=student, status=active)
      3. AuthSession (logs them straight in)
    """
    # Check email uniqueness
    result = await db.execute(select(User).where(User.email == str(data.email)))
    if result.scalar_one_or_none() is not None:
        raise ConflictError("An account with this email address already exists.")

    # Resolve the institution to enrol into. Today there is exactly one tenant;
    # if several ever exist, prefer the oldest active one (the original demo).
    # Revisit this when multi-tenant signup is introduced.
    result = await db.execute(
        select(Institution)
        .where(Institution.is_active.is_(True))
        .order_by(Institution.created_at.asc())
        .limit(1)
    )
    institution = result.scalar_one_or_none()
    if institution is None:
        raise NotFoundError("No institution is available for registration.")

    # Create user
    user = User(
        email=str(data.email),
        hashed_password=hash_password(data.password),
        full_name=data.full_name,
    )
    db.add(user)
    await db.flush()  # Insert user before membership references it

    # Create membership (student in the existing institution)
    membership = Membership(
        user_id=user.id,
        institution_id=institution.id,
        role="student",
        status="active",
    )
    db.add(membership)

    # Create auth session (self-signup logs straight in)
    auth_session = AuthSession(
        user_id=user.id,
        institution_id=institution.id,
        ip_address=ip_address,
        user_agent=user_agent,
        expires_at=_session_expires_at(),
    )
    db.add(auth_session)

    await db.commit()

    await db.refresh(user)
    await db.refresh(membership)
    await db.refresh(auth_session)

    return user, membership, auth_session


# ---------------------------------------------------------------------------
# Login
# ---------------------------------------------------------------------------


async def login(
    db: AsyncSession,
    data: LoginRequest,
    ip_address: str | None,
    user_agent: str | None,
) -> tuple[User, Membership, AuthSession]:
    """
    Verifies credentials and creates a new session.
    Always returns the same generic error to prevent email enumeration.
    """
    _invalid = UnauthorizedError("Invalid email or password.")

    result = await db.execute(
        select(User).where(
            User.email == str(data.email),
            User.deleted_at.is_(None),
        )
    )
    user = result.scalar_one_or_none()

    # Deliberately check hashed_password before verify so timing is consistent
    if user is None or user.hashed_password is None:
        raise _invalid
    if not verify_password(data.password, user.hashed_password):
        raise _invalid
    if not user.is_active:
        raise UnauthorizedError("This account has been deactivated. Contact your administrator.")

    # Find best membership: prefer institution_admin, then first active
    result = await db.execute(
        select(Membership).where(
            Membership.user_id == user.id,
            Membership.status == "active",
        )
    )
    memberships = list(result.scalars().all())
    if not memberships:
        raise UnauthorizedError("No active institution membership found for this account.")

    membership = next(
        (m for m in memberships if m.role == "institution_admin"),
        memberships[0],
    )

    # Record login time
    user.last_login_at = datetime.now(UTC)

    auth_session = AuthSession(
        user_id=user.id,
        institution_id=membership.institution_id,
        ip_address=ip_address,
        user_agent=user_agent,
        expires_at=_session_expires_at(),
    )
    db.add(auth_session)
    await db.commit()

    await db.refresh(user)
    await db.refresh(auth_session)

    return user, membership, auth_session


# ---------------------------------------------------------------------------
# Logout
# ---------------------------------------------------------------------------


async def logout(db: AsyncSession, session_id: uuid.UUID) -> None:
    result = await db.execute(select(AuthSession).where(AuthSession.id == session_id))
    session = result.scalar_one_or_none()
    if session and session.revoked_at is None:
        session.revoked_at = datetime.now(UTC)
        await db.commit()


# ---------------------------------------------------------------------------
# Refresh tokens — invalidates old session, issues new one (token rotation)
# ---------------------------------------------------------------------------


async def refresh(
    db: AsyncSession,
    refresh_token_str: str,
    ip_address: str | None,
    user_agent: str | None,
) -> tuple[User, Membership, AuthSession]:
    from app.core.exceptions import InvalidTokenError
    from app.core.security import decode_token

    try:
        payload = decode_token(refresh_token_str)
    except InvalidTokenError as err:
        raise UnauthorizedError(
            "Refresh token is invalid or expired. Please log in again."
        ) from err

    if payload.type != "refresh":
        raise UnauthorizedError("Invalid token type.")

    session_id = uuid.UUID(payload.jti)
    user_id = uuid.UUID(payload.sub)
    now = datetime.now(UTC)

    # Validate the old session (must be valid to prevent replay)
    result = await db.execute(
        select(AuthSession).where(
            AuthSession.id == session_id,
            AuthSession.revoked_at.is_(None),
            AuthSession.expires_at > now,
        )
    )
    old_session = result.scalar_one_or_none()
    if old_session is None:
        raise UnauthorizedError("Refresh token has expired or been revoked. Please log in again.")

    # Revoke old session (token rotation — prevents refresh token reuse)
    old_session.revoked_at = now

    # Validate user
    result = await db.execute(
        select(User).where(
            User.id == user_id,
            User.is_active.is_(True),
            User.deleted_at.is_(None),
        )
    )
    user = result.scalar_one_or_none()
    if user is None:
        raise UnauthorizedError("Account not found or deactivated.")

    # Resolve membership for the new session
    result = await db.execute(
        select(Membership).where(
            Membership.user_id == user.id,
            Membership.status == "active",
        )
    )
    memberships = list(result.scalars().all())
    if not memberships:
        raise UnauthorizedError("No active membership found.")

    membership = next(
        (m for m in memberships if m.role == "institution_admin"),
        memberships[0],
    )

    # Create replacement session
    new_session = AuthSession(
        user_id=user.id,
        institution_id=membership.institution_id,
        ip_address=ip_address,
        user_agent=user_agent,
        expires_at=_session_expires_at(),
    )
    db.add(new_session)
    await db.commit()
    await db.refresh(new_session)

    return user, membership, new_session


# ---------------------------------------------------------------------------
# Get current user profile with active memberships
# ---------------------------------------------------------------------------


async def get_me(
    db: AsyncSession,
    user_id: uuid.UUID,
) -> tuple[User, list[Membership]]:
    result = await db.execute(
        select(User)
        .options(selectinload(User.memberships))
        .where(
            User.id == user_id,
            User.deleted_at.is_(None),
        )
    )
    user = result.scalar_one_or_none()
    if user is None:
        raise NotFoundError("User not found.")

    active_memberships = [m for m in user.memberships if m.status == "active"]
    return user, active_memberships


# ---------------------------------------------------------------------------
# Self-service profile update
# ---------------------------------------------------------------------------


async def update_profile(
    db: AsyncSession,
    user_id: uuid.UUID,
    data: ProfileUpdateRequest,
) -> tuple[User, list[Membership]]:
    """Apply a partial profile update. Only fields explicitly present in the
    request body are written (PATCH semantics via ``model_fields_set``)."""
    result = await db.execute(
        select(User)
        .options(selectinload(User.memberships))
        .where(User.id == user_id, User.deleted_at.is_(None))
    )
    user = result.scalar_one_or_none()
    if user is None:
        raise NotFoundError("User not found.")

    fields = data.model_dump(exclude_unset=True)
    for key, value in fields.items():
        setattr(user, key, value)

    await db.commit()
    await db.refresh(user)

    active_memberships = [m for m in user.memberships if m.status == "active"]
    return user, active_memberships


# ---------------------------------------------------------------------------
# Avatar upload / removal — self-service profile photo
# ---------------------------------------------------------------------------


async def _load_user_with_memberships(
    db: AsyncSession, user_id: uuid.UUID
) -> User:
    result = await db.execute(
        select(User)
        .options(selectinload(User.memberships))
        .where(User.id == user_id, User.deleted_at.is_(None))
    )
    user = result.scalar_one_or_none()
    if user is None:
        raise NotFoundError("User not found.")
    return user


async def set_avatar(
    db: AsyncSession,
    user_id: uuid.UUID,
    file_bytes: bytes,
) -> tuple[User, list[Membership]]:
    """Store an uploaded image as the user's avatar, replacing any previous one.

    The previous on-disk file (if we managed it) is deleted only after the new
    URL is committed, so a failed write never leaves the user without an avatar.
    """
    user = await _load_user_with_memberships(db, user_id)

    # Validate + persist before touching the row — raises on bad input.
    new_url = storage.save_avatar_file(file_bytes)
    old_url = user.avatar_url
    user.avatar_url = new_url

    await db.commit()
    await db.refresh(user)

    storage.delete_avatar_file(old_url)

    active_memberships = [m for m in user.memberships if m.status == "active"]
    return user, active_memberships


async def clear_avatar(
    db: AsyncSession,
    user_id: uuid.UUID,
) -> tuple[User, list[Membership]]:
    """Remove the user's avatar and delete the backing file if we own it."""
    user = await _load_user_with_memberships(db, user_id)

    old_url = user.avatar_url
    user.avatar_url = None

    await db.commit()
    await db.refresh(user)

    storage.delete_avatar_file(old_url)

    active_memberships = [m for m in user.memberships if m.status == "active"]
    return user, active_memberships


# ---------------------------------------------------------------------------
# Change password — revokes all OTHER sessions to flush stolen credentials
# ---------------------------------------------------------------------------


async def change_password(
    db: AsyncSession,
    user_id: uuid.UUID,
    current_session_id: uuid.UUID,
    data: ChangePasswordRequest,
) -> None:
    result = await db.execute(
        select(User).where(User.id == user_id, User.deleted_at.is_(None))
    )
    user = result.scalar_one_or_none()
    if user is None:
        raise NotFoundError("User not found.")

    if user.hashed_password is None or not verify_password(
        data.current_password, user.hashed_password
    ):
        raise BadRequestError("Your current password is incorrect.")

    if verify_password(data.new_password, user.hashed_password):
        raise BadRequestError("Your new password must be different from the current one.")

    user.hashed_password = hash_password(data.new_password)

    # Security hygiene: a password change invalidates every other session so a
    # compromised credential can't keep a foothold. The current session stays.
    now = datetime.now(UTC)
    await db.execute(
        sql_update(AuthSession)
        .where(
            AuthSession.user_id == user_id,
            AuthSession.id != current_session_id,
            AuthSession.revoked_at.is_(None),
        )
        .values(revoked_at=now)
    )
    await db.commit()


# ---------------------------------------------------------------------------
# Active sessions — transparent "where you're signed in" view
# ---------------------------------------------------------------------------


async def list_sessions(
    db: AsyncSession,
    user_id: uuid.UUID,
) -> list[AuthSession]:
    """Return the user's live (non-revoked, non-expired) sessions, newest first."""
    now = datetime.now(UTC)
    result = await db.execute(
        select(AuthSession)
        .where(
            AuthSession.user_id == user_id,
            AuthSession.revoked_at.is_(None),
            AuthSession.expires_at > now,
        )
        .order_by(AuthSession.created_at.desc())
    )
    return list(result.scalars().all())


async def revoke_session(
    db: AsyncSession,
    user_id: uuid.UUID,
    session_id: uuid.UUID,
) -> None:
    """Revoke a single session the user owns (sign out one device)."""
    result = await db.execute(
        select(AuthSession).where(
            AuthSession.id == session_id,
            AuthSession.user_id == user_id,
        )
    )
    session = result.scalar_one_or_none()
    if session is None:
        raise NotFoundError("Session not found.")
    if session.revoked_at is None:
        session.revoked_at = datetime.now(UTC)
        await db.commit()


async def revoke_other_sessions(
    db: AsyncSession,
    user_id: uuid.UUID,
    keep_session_id: uuid.UUID,
) -> int:
    """Sign out everywhere except the current session. Returns count revoked."""
    now = datetime.now(UTC)
    result = await db.execute(
        sql_update(AuthSession)
        .where(
            AuthSession.user_id == user_id,
            AuthSession.id != keep_session_id,
            AuthSession.revoked_at.is_(None),
        )
        .values(revoked_at=now)
    )
    await db.commit()
    return result.rowcount or 0
