"""
Topic service layer.

Topics form a tree using a materialized path strategy.
Path format: /{uuid}/{uuid}/... — computed before insert using pre-generated UUIDs.
Since UUIDs are generated by Python (not the DB), we always know the path before inserting.
"""

import uuid

from sqlalchemy import or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import ConflictError, ForbiddenError, NotFoundError
from app.models.item_topic_link import ItemTopicLink
from app.models.topic import Topic
from app.schemas.topics import TopicCreate, TopicOut, TopicTree, TopicUpdate

# ---------------------------------------------------------------------------
# CRUD
# ---------------------------------------------------------------------------


async def create_topic(
    db: AsyncSession,
    data: TopicCreate,
    institution_id: uuid.UUID | None,
    created_by_id: uuid.UUID,
) -> Topic:
    parent: Topic | None = None
    if data.parent_id:
        result = await db.execute(select(Topic).where(Topic.id == data.parent_id))
        parent = result.scalar_one_or_none()
        if parent is None:
            raise NotFoundError(f"Parent topic '{data.parent_id}' not found.")
        # Non-superadmin users can only add children within their own institution
        if institution_id is not None and parent.institution_id != institution_id:
            raise ForbiddenError("Parent topic belongs to a different institution.")

    # Pre-generate ID so we can compute the materialized path before inserting
    new_id = uuid.uuid4()
    if parent:
        path = f"{parent.path}/{new_id}"
        level = parent.level + 1
    else:
        path = f"/{new_id}"
        level = 0

    topic = Topic(
        id=new_id,
        institution_id=institution_id,
        parent_id=data.parent_id,
        name=data.name,
        slug=data.slug,
        path=path,
        level=level,
        description=data.description,
        display_order=data.display_order,
        created_by_id=created_by_id,
    )

    db.add(topic)
    try:
        await db.flush()
        await db.commit()
    except IntegrityError as err:
        await db.rollback()
        raise ConflictError(
            "A topic with this path already exists. "
            "This should not happen with UUID paths — please retry."
        ) from err

    await db.refresh(topic)
    return topic


async def get_topic(
    db: AsyncSession,
    topic_id: uuid.UUID,
    institution_id: uuid.UUID | None,
) -> Topic:
    stmt = select(Topic).where(Topic.id == topic_id)
    if institution_id is not None:
        stmt = stmt.where(
            or_(Topic.institution_id == institution_id, Topic.institution_id.is_(None))
        )

    result = await db.execute(stmt)
    topic = result.scalar_one_or_none()
    if topic is None:
        raise NotFoundError(f"Topic '{topic_id}' not found.")
    return topic


async def list_topics(
    db: AsyncSession,
    institution_id: uuid.UUID | None,
    parent_id: uuid.UUID | None = None,
    include_inactive: bool = False,
    limit: int = 100,
    offset: int = 0,
) -> list[Topic]:
    stmt = select(Topic)
    if institution_id is not None:
        stmt = stmt.where(
            or_(Topic.institution_id == institution_id, Topic.institution_id.is_(None))
        )
    if parent_id is not None:
        stmt = stmt.where(Topic.parent_id == parent_id)
    if not include_inactive:
        stmt = stmt.where(Topic.is_active.is_(True))
    stmt = stmt.order_by(Topic.path).limit(limit).offset(offset)

    result = await db.execute(stmt)
    return list(result.scalars().all())


async def update_topic(
    db: AsyncSession,
    topic_id: uuid.UUID,
    data: TopicUpdate,
    institution_id: uuid.UUID | None,
) -> Topic:
    topic = await get_topic(db, topic_id, institution_id)

    updates = data.model_dump(exclude_unset=True)
    # Path and level are NOT updatable — moving a topic requires a dedicated
    # 'move' operation (Phase 3) to atomically rebuild all descendant paths.
    updates.pop("path", None)
    updates.pop("level", None)

    for field, value in updates.items():
        setattr(topic, field, value)

    await db.commit()
    await db.refresh(topic)
    return topic


async def delete_topic(
    db: AsyncSession,
    topic_id: uuid.UUID,
    institution_id: uuid.UUID | None,
) -> None:
    """
    Soft-deletes a topic by setting is_active=False.
    Refuses if any items are still linked to this topic.
    """
    topic = await get_topic(db, topic_id, institution_id)

    result = await db.execute(
        select(ItemTopicLink).where(ItemTopicLink.topic_id == topic_id).limit(1)
    )
    if result.scalar_one_or_none() is not None:
        raise ConflictError(
            "Cannot deactivate a topic that has items linked to it. "
            "Remove or reassign item-topic links first."
        )

    topic.is_active = False
    await db.commit()


# ---------------------------------------------------------------------------
# Tree building
# ---------------------------------------------------------------------------


async def get_topic_tree(
    db: AsyncSession,
    institution_id: uuid.UUID | None,
    root_id: uuid.UUID | None = None,
) -> list[TopicTree]:
    """
    Returns a nested tree of active topics.
    Ordering by path guarantees parents always appear before their children
    (because a child's path is always a prefix extension of its parent's path).
    """
    stmt = select(Topic).where(Topic.is_active.is_(True))
    if institution_id is not None:
        stmt = stmt.where(
            or_(Topic.institution_id == institution_id, Topic.institution_id.is_(None))
        )

    if root_id is not None:
        result = await db.execute(select(Topic).where(Topic.id == root_id))
        root = result.scalar_one_or_none()
        if root is None:
            raise NotFoundError(f"Root topic '{root_id}' not found.")
        stmt = stmt.where(Topic.path.like(f"{root.path}%"))

    stmt = stmt.order_by(Topic.path)
    result = await db.execute(stmt)
    flat = list(result.scalars().all())

    return _build_tree(flat)


def _build_tree(topics: list[Topic]) -> list[TopicTree]:
    """
    Build a nested TopicTree from a flat list sorted by materialized path.
    Because path-sorted order guarantees parent before child, we can build
    the entire tree in a single O(n) pass.
    """
    id_to_node: dict[uuid.UUID, TopicTree] = {}
    roots: list[TopicTree] = []

    for topic in topics:
        # Validate via TopicOut first — avoids triggering the lazy-loaded
        # Topic.children ORM relationship when TopicTree.model_validate reads attributes.
        node = TopicTree(**TopicOut.model_validate(topic).model_dump())
        id_to_node[topic.id] = node

        if topic.parent_id is None or topic.parent_id not in id_to_node:
            roots.append(node)
        else:
            id_to_node[topic.parent_id].children.append(node)

    return roots
