"""domain3 learning engine

Revision ID: 57748feedb2d
Revises: ecd8e501b03d
Create Date: 2026-05-16 13:23:56.571878

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57748feedb2d"
down_revision: str | Sequence[str] | None = "ecd8e501b03d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curricula",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_exam", sa.String(length=100), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("enrollment_type", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curricula_institution_id"), "curricula", ["institution_id"], unique=False
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("curriculum_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assignment_type", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("item_count_target", sa.Integer(), nullable=True),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("passing_score_percent", sa.Integer(), nullable=True),
        sa.Column("show_answers_after", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["curriculum_id"], ["curricula.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignments_curriculum_id"), "assignments", ["curriculum_id"], unique=False
    )
    op.create_table(
        "card_states",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("difficulty", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("stability", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("retrievability", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "item_id"),
    )
    op.create_index(op.f("ix_card_states_due_at"), "card_states", ["due_at"], unique=False)
    op.create_index(op.f("ix_card_states_user_id"), "card_states", ["user_id"], unique=False)
    op.create_table(
        "curriculum_enrollments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("curriculum_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("enrolled_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["curriculum_id"], ["curricula.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["enrolled_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("curriculum_id", "user_id", name="uq_enrollment_curriculum_user"),
    )
    op.create_index(
        op.f("ix_curriculum_enrollments_curriculum_id"),
        "curriculum_enrollments",
        ["curriculum_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_curriculum_enrollments_user_id"),
        "curriculum_enrollments",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_thetas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("theta", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("theta_se", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("responses_used", sa.Integer(), nullable=False),
        sa.Column("prior_weight", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "topic_id", name="uq_user_theta_user_topic"),
    )
    op.create_index(op.f("ix_user_thetas_user_id"), "user_thetas", ["user_id"], unique=False)
    op.create_table(
        "practice_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("curriculum_id", sa.UUID(), nullable=True),
        sa.Column("session_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("items_target", sa.Integer(), nullable=True),
        sa.Column("items_delivered", sa.Integer(), nullable=False),
        sa.Column("items_correct", sa.Integer(), nullable=False),
        sa.Column("score_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("theta_start", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("theta_end", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("client_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_id"],
            ["curricula.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_practice_sessions_institution_id"),
        "practice_sessions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_sessions_user_id"), "practice_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "responses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("item_version_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("primary_topic_id", sa.UUID(), nullable=True),
        sa.Column("selected_option_id", sa.UUID(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("theta_at_response", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("theta_domain_at_response", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("fsrs_rating", sa.Integer(), nullable=True),
        sa.Column("is_timed_out", sa.Boolean(), nullable=False),
        sa.Column("is_flagged_by_student", sa.Boolean(), nullable=False),
        sa.Column("was_skipped", sa.Boolean(), nullable=False),
        sa.Column("scoring_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_version_id"],
            ["item_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selected_option_id"],
            ["options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice_sessions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_responses_created_at"), "responses", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_responses_institution_id"), "responses", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_responses_item_id"), "responses", ["item_id"], unique=False)
    op.create_index(op.f("ix_responses_session_id"), "responses", ["session_id"], unique=False)
    op.create_index(op.f("ix_responses_user_id"), "responses", ["user_id"], unique=False)
    op.create_table(
        "review_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("response_id", sa.BigInteger(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("state_before", sa.String(length=20), nullable=False),
        sa.Column("difficulty_before", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("stability_before", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("state_after", sa.String(length=20), nullable=False),
        sa.Column("difficulty_after", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("stability_after", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("scheduled_interval_days", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("elapsed_days", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["responses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice_sessions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_logs_item_id"), "review_logs", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_review_logs_reviewed_at"), "review_logs", ["reviewed_at"], unique=False
    )
    op.create_index(op.f("ix_review_logs_user_id"), "review_logs", ["user_id"], unique=False)
    op.create_table(
        "theta_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("theta", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("theta_se", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("responses_used", sa.Integer(), nullable=False),
        sa.Column("trigger_response_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trigger_response_id"],
            ["responses.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_theta_history_created_at"), "theta_history", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_theta_history_user_id"), "theta_history", ["user_id"], unique=False)
    op.create_foreign_key(
        "fk_items_current_version_id",
        "items",
        "item_versions",
        ["current_version_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_items_current_version_id", "items", type_="foreignkey")
    op.drop_index(op.f("ix_theta_history_user_id"), table_name="theta_history")
    op.drop_index(op.f("ix_theta_history_created_at"), table_name="theta_history")
    op.drop_table("theta_history")
    op.drop_index(op.f("ix_review_logs_user_id"), table_name="review_logs")
    op.drop_index(op.f("ix_review_logs_reviewed_at"), table_name="review_logs")
    op.drop_index(op.f("ix_review_logs_item_id"), table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_index(op.f("ix_responses_user_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_session_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_item_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_institution_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_created_at"), table_name="responses")
    op.drop_table("responses")
    op.drop_index(op.f("ix_practice_sessions_user_id"), table_name="practice_sessions")
    op.drop_index(op.f("ix_practice_sessions_institution_id"), table_name="practice_sessions")
    op.drop_table("practice_sessions")
    op.drop_index(op.f("ix_user_thetas_user_id"), table_name="user_thetas")
    op.drop_table("user_thetas")
    op.drop_index(op.f("ix_curriculum_enrollments_user_id"), table_name="curriculum_enrollments")
    op.drop_index(
        op.f("ix_curriculum_enrollments_curriculum_id"), table_name="curriculum_enrollments"
    )
    op.drop_table("curriculum_enrollments")
    op.drop_index(op.f("ix_card_states_user_id"), table_name="card_states")
    op.drop_index(op.f("ix_card_states_due_at"), table_name="card_states")
    op.drop_table("card_states")
    op.drop_index(op.f("ix_assignments_curriculum_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_curricula_institution_id"), table_name="curricula")
    op.drop_table("curricula")
    # ### end Alembic commands ###
