"""domain4 analytics domain5 system all 32 tables

Revision ID: d21dd58e384b
Revises: 57748feedb2d
Create Date: 2026-05-16 13:30:03.605188

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d21dd58e384b"
down_revision: str | Sequence[str] | None = "57748feedb2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_institution_id"), "audit_logs", ["institution_id"], unique=False
    )
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_jobs_created_at"), "background_jobs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_institution_id"),
        "background_jobs",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_job_type"), "background_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_scheduled_at"), "background_jobs", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_background_jobs_status"), "background_jobs", ["status"], unique=False)
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=True),
        sa.Column("flag_key", sa.String(length=100), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rollout_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "flag_key", name="uq_feature_flags_institution_key"),
    )
    op.create_index(op.f("ix_feature_flags_flag_key"), "feature_flags", ["flag_key"], unique=False)
    op.create_index(
        op.f("ix_feature_flags_institution_id"), "feature_flags", ["institution_id"], unique=False
    )
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=True),
        sa.Column("template_key", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "institution_id",
            "template_key",
            "channel",
            name="uq_notif_template_institution_key_channel",
        ),
    )
    op.create_index(
        op.f("ix_notification_templates_institution_id"),
        "notification_templates",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_template_key"),
        "notification_templates",
        ["template_key"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("template_key", sa.String(length=100), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("context_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_institution_id"), "notifications", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "report_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("report_type", sa.String(length=50), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schedule_cron", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_definitions_institution_id"),
        "report_definitions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_definitions_report_type"),
        "report_definitions",
        ["report_type"],
        unique=False,
    )
    op.create_table(
        "item_analytics",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("total_responses", sa.Integer(), nullable=False),
        sa.Column("correct_responses", sa.Integer(), nullable=False),
        sa.Column("avg_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("difficulty_irt", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("discrimination_irt", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("point_biserial", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("facility_index", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("flag_count", sa.Integer(), nullable=False),
        sa.Column("skip_count", sa.Integer(), nullable=False),
        sa.Column("timeout_count", sa.Integer(), nullable=False),
        sa.Column("last_calibrated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id", "institution_id"),
    )
    op.create_index(
        op.f("ix_item_analytics_institution_id"), "item_analytics", ["institution_id"], unique=False
    )
    op.create_table(
        "user_topic_mastery",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("theta", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("mastery_level", sa.String(length=20), nullable=False),
        sa.Column("total_responses", sa.Integer(), nullable=False),
        sa.Column("correct_responses", sa.Integer(), nullable=False),
        sa.Column("accuracy_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("avg_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("retention_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("items_due_count", sa.Integer(), nullable=False),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "topic_id"),
    )
    op.create_index(
        op.f("ix_user_topic_mastery_user_id"), "user_topic_mastery", ["user_id"], unique=False
    )
    op.create_table(
        "cohort_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("curriculum_id", sa.UUID(), nullable=True),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column("avg_theta", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("median_theta", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("stddev_theta", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("avg_accuracy_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("avg_retention_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("total_responses", sa.Integer(), nullable=False),
        sa.Column("mastery_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("topic_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["curriculum_id"], ["curricula.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cohort_snapshots_institution_id"),
        "cohort_snapshots",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_snapshots_snapshot_date"),
        "cohort_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cohort_snapshots_snapshot_date"), table_name="cohort_snapshots")
    op.drop_index(op.f("ix_cohort_snapshots_institution_id"), table_name="cohort_snapshots")
    op.drop_table("cohort_snapshots")
    op.drop_index(op.f("ix_user_topic_mastery_user_id"), table_name="user_topic_mastery")
    op.drop_table("user_topic_mastery")
    op.drop_index(op.f("ix_item_analytics_institution_id"), table_name="item_analytics")
    op.drop_table("item_analytics")
    op.drop_index(op.f("ix_report_definitions_report_type"), table_name="report_definitions")
    op.drop_index(op.f("ix_report_definitions_institution_id"), table_name="report_definitions")
    op.drop_table("report_definitions")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_institution_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_templates_template_key"), table_name="notification_templates"
    )
    op.drop_index(
        op.f("ix_notification_templates_institution_id"), table_name="notification_templates"
    )
    op.drop_table("notification_templates")
    op.drop_index(op.f("ix_feature_flags_institution_id"), table_name="feature_flags")
    op.drop_index(op.f("ix_feature_flags_flag_key"), table_name="feature_flags")
    op.drop_table("feature_flags")
    op.drop_index(op.f("ix_background_jobs_status"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_scheduled_at"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_job_type"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_institution_id"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_created_at"), table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index(op.f("ix_audit_logs_institution_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
