"""add exam_type to items

Revision ID: e48ce4433ba3
Revises: d21dd58e384b
Create Date: 2026-05-16 14:31:32.105553

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e48ce4433ba3"
down_revision: str | Sequence[str] | None = "d21dd58e384b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("exam_type", sa.String(length=30), nullable=True))
    op.create_index(op.f("ix_items_exam_type"), "items", ["exam_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_exam_type"), table_name="items")
    op.drop_column("items", "exam_type")
    # ### end Alembic commands ###
